### ISSUE TITLE
Will you be updating this mod?

### ISSUE THREAD

**Issue by allanonmage** [purejosh/purecoppertools#1]
My server is on 1.19.2, but at some point we'd like to move to 1.20.  Will you be updating your mod?  It seems that yours is the only copper tools mod for recent versions.

**Comment by purejosh** [comment]
Yes! I absolutely will, but since I develop for both Forge and Fabric, it's a little difficult. 

What loader are you using?

**Comment by allanonmage** [comment]
Fabric. My server is 1.19.2 and I have a ton of mods, so updating is prolly a ways off.

**Comment by purejosh** [comment]
I should have a Fabric 1.20 update within the next week or two. Forge 1.20 will be delayed while I work through updating all my mods to Fabric 1.20. 

Any additional content you'd be interested in seeing?

**Comment by allanonmage** [comment]
I didn't realize you had a whole suite of mods, they are just what I was looking for!  On first glance, I don't see any horse armor.  That would be cool, for copper, Ender, emerald, and amethyst.  And then maybe someway to add the material look to shields would be really cool, maybe even some special abilities like you're already doing.

**Comment by purejosh** [comment]
Oh, yeah, I've got quite a few mods going on. Keeps me busy, heh. 

Good to know, I'll look into adding horse armor. I was also thinking about adding lanterns or some other block type of item, just to mix it up a bit. 

I think I'll be adding shields into its own mod, but I've thought about it many times. Just something with a small bump in durability and such.

**Comment by allanonmage** [comment]
Speaking of bumps in durability, tridents def need that.  Even with using several Trident themed mods, they still have terribly low durability.  Impaled and Better Tridents are the two bigger trident mods I use.

**Comment by purejosh** [comment]
And they don't have good durability in those mods? I know impaled has awesome tridents. I'm not sure I could compete.

**Comment by allanonmage** [comment]
250 or so

The problem is that the maelstrom takes the XP, so mending on the trident can't grab the xp. #1stWorldProblem lol

**Comment by purejosh** [comment]
1.20.1 can be released soon, does that work for you? I'd hate to be the reason someone doesn't update, or have my mod excluded.

**Comment by allanonmage** [comment]
I think it's about time for me to start looking to see which mods have made the updates so far.  Lots of mods, so I was giving them all time, but Hermitcraft has already updated, so maybe things are moving faster than I thought they would

**Comment by purejosh** [comment]
Hermitcraft uses Fabric, but they're not modded like most servers. They use very, very few mods. but I can sit down this next week and crank out some updates.

**Comment by Rebel459** [comment]
Still don’t know what Hermitcraft is to this day lol… is good to see plenty of fabric mods on 1.20 already

**Comment by allanonmage** [comment]
Hermitcraft is a popular youtube/twitch smp that started like 10 or 11 years ago.

**Comment by purejosh** [comment]
This mod has been updated, and is released on [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/pure-copper-tools-fabric-forge) and [Modrinth](https://modrinth.com/mod/pure-copper-tools).
