### ISSUE TITLE
[Bug] Not able to make copper tools

### ISSUE THREAD

**Issue by wesleywithoutat** [purejosh/purecoppertools#10]
**Describe the bug**
I'm running 1.20.4 with Fabric on my server. 
When I'm in the crafting table with the recipe book open, a bunch of extra slots with no picture are there (for the copper tools) but they're all marked as Air. If I lay out the resources for, say, a copper pickaxe, there's nothing in the output box. But if I click it, it uses up the materials.

**To Reproduce**
1. Install mod
2. Doesn't work
3. 
4. 

**Screenshots**
![Screenshot 2024-09-18 152633](https://github.com/user-attachments/assets/351b22b4-a3bb-43de-83fe-0344b7cd9b20)

**Version information**
Fabric/Forge: Fabric
Loader version: 0.16.5
Mod version: 1.0.1
Mod list: Essential Commands
               RightClickHarvest
               Tree Harvester
               Universal Graves
               Pure Copper Tools
               Fabric API
               Architectury API
               JamLib
               Collective

**Comment by purejosh** [comment]
That's bizarre. Can you recreate this with only Pure Copper Tools and FAPI?

**Comment by wesleywithoutat** [comment]
I just tried that and it's still doing the exact same thing. Wesley MillerOn Sep 18, 2024, at 3:38 PM, purejosh ***@***.***> wrote:﻿
That's bizarre. Can you recreate this with only Pure Copper Tools and FAPI?

**Comment by purejosh** [comment]
Alright, I'll give it a test. It might be something that changed with FAPI, or the loader. I'll post here after I've tested it.

**Comment by wesleywithoutat** [comment]
So I was installing a new mod on my server last night, and ran into issues with missing textures on it too. Is there somewhere I can grab just the resource pack? I think that may be the issue, cause I had to go through a whole ordeal to get that other resource pack installed correctly.

**Comment by wesleywithoutat** [comment]
Sorry, I hit the wrong button there

**Comment by purejosh** [comment]
Nope, this mod doesn't have a separate resource pack. And if it were a resource pack issue, it wouldn't cause the items to be unobtainable/uncraftable, it would simply show as a black and purple square where the image of the item would be.

**Comment by purejosh** [comment]
Given that this mod was developed solely for 1.20.1, and FAPI 1.20.4 had an interaction with it, it's safe to say something changed in between the versions that broke things. That being said, I've moved on to 1.21.x, so this issue will be closed as unresolved. 

Thanks for reporting it, though. I will be removing the compatibility tag from this mod for 1.20.4.
