### ISSUE TITLE
[Bug] Copper tools and "New Recipe Unlocked!" not showing until already crafted instead of upon obtaining copper ingots

### ISSUE THREAD

**Issue by steve-the-player** [purejosh/purecoppertools#3]
**Describe the bug**
If you make the tools in the crafting table, it works just fine, but you have to already know the recipes ahead of time. They don't show up in the book. Once you craft something, it shows up in the book and gives you the "crafting recipe unlocked" text, but this should happen when you obtain copper ingots for the first time, not after you've already crafted them into things

**To Reproduce**
1. Get copper
2. open crafting table
3. click book
4. (search copper or filter by tools)

**Screenshots**
<img width="1512" alt="Screenshot 2023-11-16 at 11 54 56 AM" src="https://github.com/purejosh/purecoppertools/assets/61434698/be4bb529-82a2-4345-a3d6-9e0a59ffba16">
<img width="1512" alt="Screenshot 2023-11-16 at 11 54 58 AM" src="https://github.com/purejosh/purecoppertools/assets/61434698/91fb6f87-c7ad-4845-a054-02b4c173e9e0">
<img width="1512" alt="Screenshot 2023-11-16 at 11 55 06 AM" src="https://github.com/purejosh/purecoppertools/assets/61434698/39b401f0-0e8d-4aeb-8ef9-ab4d09281a49">
<img width="1512" alt="Screenshot 2023-11-16 at 12 12 41 PM" src="https://github.com/purejosh/purecoppertools/assets/61434698/63e3428c-60a3-428f-af28-ef356d27d153">
<img width="1512" alt="Screenshot 2023-11-16 at 12 12 51 PM" src="https://github.com/purejosh/purecoppertools/assets/61434698/74fefa1a-8f03-4774-b555-e7ff1113a3f0">

**Version information**
Fabric/Forge: Fabric 
Loader version: 0.14.24
Mod version: 1.0.0
Mod list: 
3D Skin Layers
All The Fan Made Discs
BetterF3
Boat Item View
CIT Resewn
Chunky
Clumps
CorgiLib
Cosmetic Armor
CraftPresence
Don't Clear Chat History
Debugify
Exotelcraft
Explorer's Compass
FallingTree
Fastload
Forge Config API Port
Galosphere
Gilded Sherds
Glass Armor
ImmediatelyFast
Nature's Compass
No Chat Reports
Oh My Sherd
Philips Ruins
Pure Copper Tools
Quad
Resource Pack Overrides
Remove Reloading Screen
Shoulder Surfing Reloaded
Hellion's Sniffer+
Terra
TerraBlender
Towns and Towers
Traveler's Titles
Xaero's World Map
Xaero's Minimap
YUNG's API
AdvancementInfo
Animatica
AntiGhost
Architectury API
Athena
Balm
BCLib
BetterEnd
BetterNether
Better Archeology
Biome Makeover
Biome Moss
Blur (Fabric)
Bobby
Borderless Mining
Bad Wither No Cookie - Reloaded
Capes
Cherished Worlds
Chipped
Chunks fade in
Cinderscapes
Cloth Config API
Collective
Continuity
Return Copper Horns
Cristel Lib
Cull Leaves
DashLoader
Dawn API
Durability Tooltip
Dynamic FPS
e4mc
Elytra Slot
Enhanced Block Entities
[EMF] Entity Model Features
[ETF] Entity Texture Features
Entity Culling
Fabric API
Fabric Language Kotlin
Fabric Seasons
FabricSkyboxes
Fadeless
FastQuit
FerriteCore
FPS - Display
Friends&Foes (Fabric)
FabricSkyBoxes Interop
Geckolib
Global Packs
Gravity Changer (qouteall fork)
Great Big World
Hold That Chunk
Hybrid Aquatic
Immersive Portals
Indium
Inventory Pause
Just Mob Heads
LambDynamicLights
Language Reload
Lighty
Lithium
Logical Zoom
Main Menu Credits
Memory Leak Fix
MES - Moog's End Structures
MidnightLib
MixinTrace
Model Gap Fix
ModernFix
Mod Menu
More Chat History
More Culling
Netherenditions
Better Nether Map
No Resource Pack Warnings
Not Just Biomes
Polymorph
Promenade
Puzzle
qrafty's End Villages
Reese's Sodium Options
Repurposed Structures - Quilt/Fabric
Resourceful Lib
RPGTitles
Saturated
Sculk Depths
Shulker Box Tooltip
Sodium Extra
Sodium
Sparse Structures
SuperMartijn642's Config Lib
SwingThrough
ToolTipFix
Trinkets
Underground Jungle
Various Starting Loot
Wakes
WearThat
YetAnotherConfigLib
Your Options Shall Be Respected (YOSBR)
Faithless
Translations for Sodium

Most of these shouldn't matter, but here it is anyways. 

**Additional context**
Crafting table is slightly bugged with this modlist, not sure why, but when you click on a recipe, IF the crafting recipe exists *cough cough*, it bugs out and doesn't show the items in the crafting GUI, just the output. Clicking on any inventory slot fixes that.

**Comment by steve-the-player** [comment]
Appears to be an issue not only with your mod, but one of the crafting/GUI api mods I have. Going to have to go through them all I guess

**Comment by purejosh** [comment]
For some stupid reason, the copper tools recipes are given when you obtain a copper block, not a copper ingot. I'll fix that and release a new version.

**Comment by purejosh** [comment]
This has been resolved in the latest version. Available on Modrinth now, or Curseforge after they approve it. Thanks for reporting this to me.
