### ISSUE TITLE
[Suggestion] Spelunkery compatibility 

### ISSUE THREAD

**Issue by steve-the-player** [purejosh/purecoppertools#4]
**Describe your proposed suggestion.**
[Spelunkery](https://modrinth.com/mod/spelunkery) completely overhauls mining, adding ~~ingots~~ _nuggets_ to all ores that don’t have them already. In addition, mining an ore drops the raw metal, and occasionally also raw metal ~~ingots~~ _nuggets_. However, even with [AlmostUnified](https://modrinth.com/mod/almost-unified) installed, I end up with two unique copper ~~ingot~~ _nugget_ recipes (because they have different textures I think).

**Comment by purejosh** [comment]
What copper ingot recipes are you speaking of? Drop some screenshots, if you wouldn't mind.

**Comment by steve-the-player** [comment]
![2023-12-18_16 36 38](https://github.com/purejosh/purecoppertools/assets/61434698/82e6ada5-9da0-489a-82c4-2a407520bf98)
![2023-12-18_16 37 38](https://github.com/purejosh/purecoppertools/assets/61434698/3dedcc26-75f5-4bdd-86b9-540387b7f083)
They should be the same thing, but they don't appear to for some reason. When Polymorph is disabled, it appears as two distinct crafting recipes.

**Comment by purejosh** [comment]
That is a copper nugget recipe, not a copper ingot recipe. I will ask AU what they think of this, and if I need to tag my nuggets to get them to merge.

**Comment by steve-the-player** [comment]
Yeah, my bad, it sure is a nugget. Had a brain fart when I was typing

**Comment by purejosh** [comment]
I believe setting the common tag is what needed to be done, here. It's been a while. The 1.21 release of this mod will include those tags. Feel free to retest in the latest release and see if that's the case! If not, of course, let me know.
