### ISSUE TITLE
[Bug] AAAAAAAAAA NO TRIM SUPPORT FOR 1.20.1

### ISSUE THREAD

**Issue by ghost** [purejosh/purecoppertools#8]
**Describe the bug**
"its a bug" -apollo the funny bird

**To Reproduce**
1. AAAAAAAAAAAAA
2. AAAAAA
3. AAAAAAA
4. doesnt let you put it in the smithing table so no trim :c

**Screenshots**

**Version information**
Fabric/Forge: FABRICCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
Loader version: 2024-06-16 LATEST STABLE
Mod version: LATEST
Mod list: DOESNT MATTER

**Additional context**
Add any other context about the problem here.'

IM BEGGING YOU TO ADD THIS I NEEEEEEEEEEEEEEEEEEEED IT AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by purejosh** [comment]
This is not a bug, this is a feature request. The suggestion form would've been much easier to fill out. 

I've been asked to add trim support to my armors many times. As soon as I've ported up to 1.21 (which is an absolute monster), I'll look into adding trim support.

**Comment by purejosh** [comment]
1.21 will include trim support, release will be within the next week.
